@@ .. @@
 ALTER TABLE payroll_runs ENABLE ROW LEVEL SECURITY;
 ALTER TABLE notifications ENABLE ROW LEVEL SECURITY;
 ALTER TABLE audit_logs ENABLE ROW LEVEL SECURITY;
+ALTER TABLE staff_individual_allowances ENABLE ROW LEVEL SECURITY;
+ALTER TABLE staff_individual_deductions ENABLE ROW LEVEL SECURITY;